# Generated by Django 2.2 on 2021-07-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adress",
            options={"verbose_name_plural": "Adressess"},
        ),
    ]
