# Generated by Django 2.2 on 2021-07-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_orderdevilevered"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdevilevered",
            name="quantity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.OrderItem",
            ),
            preserve_default=False,
        ),
    ]
