# Generated by Django 2.2 on 2021-07-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_orderdevilevered_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdevilevered",
            name="item",
        ),
    ]
