# Generated by Django 2.2 on 2021-07-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210725_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdevilevered',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
